# Generated by Django 4.2.13 on 2024-06-05 12:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='book_users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='book_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user_tab',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('au_id', models.AutoField(primary_key=True, serialize=False)),
                ('au_name', models.CharField(max_length=100)),
                ('au_bio', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bo_id', models.AutoField(primary_key=True, serialize=False)),
                ('bo_title', models.CharField(max_length=100)),
                ('bo_pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('bo_isbn', models.CharField(max_length=100)),
                ('bo_au', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False)),
                ('rv_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rv_comment', models.CharField(max_length=100)),
                ('rv_created_at', models.DateTimeField(auto_now_add=True)),
                ('rv_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.book')),
                ('rv_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
