# Generated by Django 4.2.13 on 2024-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('au_id', models.AutoField(primary_key=True, serialize=False)),
                ('au_name', models.CharField(max_length=100)),
                ('au_bio', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'author',
            },
        ),
    ]
