# Generated by Django 4.2.13 on 2024-05-31 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rv_id', models.AutoField(primary_key=True, serialize=False)),
                ('rv_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rv_comment', models.CharField(max_length=100)),
                ('rv_created_at', models.DateTimeField(auto_now_add=True)),
                ('rv_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.book')),
                ('rv_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='book.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
