# Generated by Django 4.2.13 on 2024-05-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_tab',
        ),
    ]
